name: CI for Data Cleaning

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: pip install pandas

    - name: Run data processing
      run: python main.py

    - name: Commit processed dataset
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add data/processed_dataset.csv || echo "Nothing to add"
        git commit -m "Add processed dataset" || echo "Nothing to commit"
        git push || echo "Push failed or nothing to push"
